/**
 * Utility functions for generating optimized image sources
 */

export interface ImageSources {
  original: string;
  placeholder: string;
  lowRes?: string;
}

/**
 * Generate placeholder and low-res sources for an image
 */
export function generateImageSources(originalSrc: string): ImageSources {
  if (!originalSrc) {
    return {
      original: '',
      placeholder: generatePlaceholderDataUrl(400, 300)
    };
  }

  // Extract file info
  const lastDotIndex = originalSrc.lastIndexOf('.');
  const basePath = originalSrc.substring(0, lastDotIndex);
  const extension = originalSrc.substring(lastDotIndex);

  // Generate sources
  const sources: ImageSources = {
    original: originalSrc,
    placeholder: generatePlaceholderDataUrl(400, 300)
  };

  // For large images, create low-res version path
  // In a real implementation, these would be generated by your build process
  // For now, we'll use the original and implement blur effect in CSS
  if (isLargeImage(originalSrc)) {
    // In production, you might have: `${basePath}-lowres${extension}`
    sources.lowRes = originalSrc; // Fallback to original for now
  }

  return sources;
}

/**
 * Generate a simple placeholder data URL
 */
export function generatePlaceholderDataUrl(width: number, height: number, color = '#e5e7eb'): string {
  const svg = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <rect width="100%" height="100%" fill="${color}"/>
      <text x="50%" y="50%" font-family="Arial, sans-serif" font-size="14" fill="#9ca3af" text-anchor="middle" dy=".3em">Loading...</text>
    </svg>
  `;
  
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

/**
 * Check if an image is considered "large" and would benefit from progressive loading
 */
export function isLargeImage(src: string): boolean {
  // Simple heuristic - in production you might check actual file sizes
  const sizeIndicators = [
    'Gallery', // Our gallery images are typically large
    'Cover',   // Cover images are usually large
    '.jpg',    // Assume JPGs are potentially large
    '.jpeg',
    '.png'
  ];
  
  return sizeIndicators.some(indicator => 
    src.toLowerCase().includes(indicator.toLowerCase())
  );
}

/**
 * Get optimized loading settings based on image characteristics
 */
export function getLoadingSettings(src: string) {
  const isLarge = isLargeImage(src);
  const isAboveFold = src.includes('Gallery1') || src.includes('gallery1'); // First gallery is above fold
  
  return {
    rootMargin: isAboveFold ? '0px' : '100px', // Load above-fold images immediately
    threshold: isLarge ? 0.1 : 0.25, // Lower threshold for large images
    priority: isAboveFold ? 'high' : 'normal'
  };
}

/**
 * Generate responsive image sizes based on container and device
 */
export function generateImageSizes(layout: string): string {
  switch (layout) {
    case 'masonry':
      return '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw';
    case 'grid':
      return '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw';
    case 'carousel':
    case 'fullscreen':
      return '100vw';
    default:
      return '(max-width: 768px) 100vw, 50vw';
  }
}
